import { Montserrat } from "next/font/google";
import { ThemeProvider } from "@mui/material";
import theme from "@/components/theme/theme";
import "./globals.css";

const montserrat = Montserrat({
  weight: '400',
  subsets: ['latin']
});


export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={montserrat.className}>
        <ThemeProvider theme={theme}>
          {children}
        </ThemeProvider>
      </body>
    </html>
  );
}
